name: secure_password_generator
description: A CLI application to generate secure passwords
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

homepage: https://ameeen.me/
issue_tracker: hhttps://github.com/muhd-ameen/secure_password_generator/issues
repository: https://github.com/muhd-ameen/secure_password_generator

dependencies:
  ansicolor: ^2.0.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1

